### ISSUE TITLE
Add a header including links to CodeWithAhsan Socials

### ISSUE THREAD

**Issue by AhsanAyaz** [code-with-ahsan/js-slider#2]
We need a header in this app/page that contains the social links ([facebook](https://facebook.com/codewithahsan), [twitter](https://twitter.com/codewith_ahsan), and [YouTube](https://youtube.com/CodeWithAhsan)) of Code with Ahsan.
Header sample:
https://focusdoro.app/#/home

On the left, it should say "JS Image Slider". On the right, there should be three icons (facebook, twitter, youtube) with links to them. 
The links should open in a new tab.

**Comment by prerit2001** [comment]
Please Assign me this task.

**Comment by AhsanAyaz** [comment]
> Please Assign me this task.

Please go ahead and start working on it 👍🏼

**Comment by jukha** [comment]
I can work on this issue.  Please assign me this.

**Comment by prerit2001** [comment]
Done with the assigned task. Please merge it and label this with hacktoberfest-accepted.

**Comment by AhsanAyaz** [comment]
Closed by #4
